version: "3.9"

services:
    rabbitmq:
        image: masstransit/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
    # app:
    #     build:
    #         context: .
    #         dockerfile: aspnetapp/Dockerfile
    #     # depends_on:
    #     #     - mysql
    #     #     - seq
    #     environment:
    #         ASPNETCORE_ENVIRONMENT: Development
    #         # SEQ_SERVER_URL: http://seq:5341
    #     ports:
    #         - 7131:80
    #         - 5011:443
    # stub:
    #     build:
    #         context: .
    #         dockerfile: ServiceStub/Dockerfile
    #     depends_on:
    #         - seq
    #     environment:
    #         ASPNETCORE_ENVIRONMENT: Development
    #         # SEQ_SERVER_URL: http://seq:5341
    #     ports:
    #         - 12345:80
    # mysql:
    #     image: mysql:5.7
    #     environment:
    #         MYSQL_DATABASE: DotNetTraining
    #         MYSQL_ROOT_PASSWORD: 240690
    #     volumes:
    #         - ./dbSetup.sql:/docker-entrypoint-initdb.d/dbSetup.sql
    #         - vdata:/var/lib/mysql
    # mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     environment:
    #         ACCEPT_EULA: Y
    #         SA_PASSWORD: 24061990
    #         MSSQL_PID: Express
    #     ports:
    #         - 1433:1433
    # seq:
    #     image: datalust/seq
    #     restart: unless-stopped
    #     environment:
    #         - ACCEPT_EULA=Y
    #     volumes:
    #         - vdata:/data
    #     ports:
    #         - 8080:80
    #         - 5342:5341
# volumes:
#     vdata:
