version: '3.9'

services:
    app:
        build: .
        ports:
            - 5000:80
        depends_on:
            - mysql
            - seq
        volumes:
            - app_data:/var/lib/aspnet
        # networks:
        #     - app_network
    mysql:
        image: mysql:5.7
        volumes:
            - app_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: todos
            MYSQL_ROOT_PASSWORD: secret
    seq:
        image: datalust/seq
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        volumes:
            - app_data:/var/lib/seq
        ports:
            - 5342:5341
            - 8080:80
        # networks:
        #     - app_network
volumes:
    app_data:
# networks:
#     app_network:
#       driver: bridge

    # mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     environment:
    #         ACCEPT_EULA: Y
    #         SA_PASSWORD: 24061990
    #         MSSQL_PID: Express
    #     ports:
    #         - 1433:1433
    #     volumes:
    #         - app_data:/data/mssql
    #     # networks:
    #     #     - app_network