version: '3.9'

services:
    app:
        build: .
        depends_on:
            - mysql
            - seq
        volumes:
            - vdata:/var/lib/aspnet
        ports:
            - 7131:80
        # networks:
        #     - app_network
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: DotNetTraining
            MYSQL_ROOT_PASSWORD: 240690
        volumes:
            - ./dbSetup.sql:/docker-entrypoint-initdb.d/dbSetup.sql
            - vdata:/var/lib/mysql
        # ports:
        #     - 3306:3306
    seq:
        image: datalust/seq
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        volumes:
            - vdata:/var/lib/seq
        ports:
            - 5342:5341
            - 8080:80
        # networks:
        #     - app_network
volumes:
    vdata:
# networks:
#     app_network:
#       driver: bridge

    # mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     environment:
    #         ACCEPT_EULA: Y
    #         SA_PASSWORD: 24061990
    #         MSSQL_PID: Express
    #     ports:
    #         - 1433:1433
    #     volumes:
    #         - vdata:/data/mssql
    #     # networks:
    #     #     - app_network