version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: aspnetapp/Dockerfile
        depends_on:
            - mysql
            - seq
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            # SEQ_SERVER_URL: http://seq:5341
        volumes:
            - ./aspnetapp:/src
        ports:
            - 7131:80
            - 5011:443
        # working_dir: /src/aspnetapp
        # command: "dotnet aspnetapp.dll"
    # stub:
    #     build:
    #         context: .
    #         dockerfile: ServiceStub/Dockerfile
    #     # depends_on:
    #     #     - seq
    #     environment:
    #         ASPNETCORE_ENVIRONMENT: Development
    #         # SEQ_SERVER_URL: http://seq:5341
    #     volumes:
    #         - ./ServiceStub:/src
    #     ports:
    #         - 12345:80
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: DotNetTraining
            MYSQL_ROOT_PASSWORD: 240690
        volumes:
            - ./dbSetup.sql:/docker-entrypoint-initdb.d/dbSetup.sql
            - vdata:/lib/mysql
        # ports:
        #     - 3306:3306
    seq:
        image: datalust/seq
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
        volumes:
            - vdata:/lib/seq
        ports:
            - 5342:5341
            - 8080:80
volumes:
    vdata:
# networks:
#     app_network:
#       driver: bridge

    # mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     environment:
    #         ACCEPT_EULA: Y
    #         SA_PASSWORD: 24061990
    #         MSSQL_PID: Express
    #     ports:
    #         - 1433:1433
    #     volumes:
    #         - vdata:/data/mssql
