version: "3"
services:
    app:
        build: .
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: secret
            MSSQL_PID: Express
        ports:
            - 1433:1433
