###
http://localhost:7131/api/users/2

### ### ###
http://localhost:7237/api/enrollments
###
POST http://localhost:7237/api/enrollments
content-type: application/json

{
    "UserId": "2",
    "CourseId": "1"
}
###
POST http://localhost:7237/api/enrollments/sync
content-type: application/json

{
    "UserId": "3",
    "CourseId": "1"
}


### ### ###
http://localhost:7124/api/reports
###
