###
https://localhost:7131/api/users/
###
http://localhost:5011/api/users/

### ### ###
http://localhost:7237/api/enrollments
###
POST http://localhost:7237/api/enrollments
content-type: application/json

{
    "Id": "1",
    "UserId": "2",
    "CourseId": "123"
}
###
PUT https://localhost:7237/api/enrollments/4
content-type: application/json

{

}
###
DELETE https://localhost:7237/api/enrollments/99
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### ### ###
