###
https://localhost:7275/api/jwt/public


### ### ### 
POST https://localhost:7275/users/revoke
content-type: application/json

{
    "AccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImJjNzM2OGI2LWI1NmItNDEwZS1hZTQzLTY3NmM3NmJjZTU0NCIsImVtYWlsIjoibWVtYmVyMUBpbmZvLnZuIiwianRpIjoiYmIzNmZhYjUtY2ZhOS00MjQzLWEyYTYtMjY4YjlhYzA5NmE1IiwibmFtZWlkIjoiYmM3MzY4YjYtYjU2Yi00MTBlLWFlNDMtNjc2Yzc2YmNlNTQ0IiwibmFtZSI6Im1lbWJlcjFAaW5mby52biIsInJvbGUiOiJNZW1iZXIiLCJuYmYiOjE2NjYxNjY5OTAsImV4cCI6MTY2NjI1MzM5MCwiaWF0IjoxNjY2MTY2OTkwfQ.eErjKYfKETxVNKbG6dH-ffaMOFC2UBVyhYw1kJl87fE",
    "RefreshToken": "67EMYR7U71QN63O42VEPS2VWM778b8986-2830-43dc-92c5-7be936782edb"
}


### ### ### 
POST https://localhost:7275/users/token
content-type: application/json

{
    "Email": "member2@info.vn",
    "Password": "member2"
}


### ### ### 
POST https://localhost:7275/users/refreshToken
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsImVtYWlsIjoidXNlcjFAaW5mby52biIsImp0aSI6IjU2ZTJiODNkLTMzMjgtNGUzNS1hMGI0LThlNzU4YTUwYWYyOCIsIm5hbWVpZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsIm5hbWUiOiJ1c2VyMUBpbmZvLnZuIiwibmJmIjoxNjY2MTY1ODE1LCJleHAiOjE2NjYyNTIyMTUsImlhdCI6MTY2NjE2NTgxNX0.j6EaTeDGbNNvy_dd7f6wm5YYOWCoyj1qGNLuwspR5gM

{
    "AccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImQzMzg4NThmLWM4MTAtNDQwZC05YzFhLTliMGJiZjU0ODEyYiIsImVtYWlsIjoiYWRtaW4xQGluZm8udm4iLCJqdGkiOiIxZDRlMDFiNi01OWE4LTQ3YWUtYTI5Mi05ODllZjZlNzExYTUiLCJuYW1laWQiOiJkMzM4ODU4Zi1jODEwLTQ0MGQtOWMxYS05YjBiYmY1NDgxMmIiLCJuYW1lIjoiYWRtaW4xQGluZm8udm4iLCJQZXJtaXNzaW9uIjoiQWRtaW4uTWFuYWdlLkZ1bGwiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2NjYxNjUzNDIsImV4cCI6MTY2NjI1MTc0MiwiaWF0IjoxNjY2MTY1MzQyfQ.PnbxZ23tIYV4dJJAp7QSNcP2fSEdTMFf7NnHJQ3l5NE",
    "RefreshToken": "G88CPDXBJFTUT5ABTXM3T6HS3d6f23b22-c775-414c-be5f-4db603c93b56"
}


### ### ### 
https://localhost:7275/users
###
https://localhost:7275/users/staff1@info.vn
###
POST https://localhost:7275/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImQzMzg4NThmLWM4MTAtNDQwZC05YzFhLTliMGJiZjU0ODEyYiIsImVtYWlsIjoiYWRtaW4xQGluZm8udm4iLCJqdGkiOiIzYjgwYWJiNS04Y2Y5LTQ3NzYtYTEzOC0xMjYxMDYxMmE5NjMiLCJuYW1laWQiOiJkMzM4ODU4Zi1jODEwLTQ0MGQtOWMxYS05YjBiYmY1NDgxMmIiLCJuYW1lIjoiYWRtaW4xQGluZm8udm4iLCJQZXJtaXNzaW9uIjoiQWRtaW4uTWFuYWdlLkZ1bGwiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2NjYxNjU2MDUsImV4cCI6MTY2NjI1MjAwNSwiaWF0IjoxNjY2MTY1NjA1fQ.EXnBUvsHC34drFyt-W89ggRd5XD10-cmuiXsicO_TYs

{
    "Email": "user2@info.vn",
    "Password": "user2",
    "Role": "Member"
}
###
PUT https://localhost:7275/users/admin2@info.vn
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsImVtYWlsIjoidXNlcjFAaW5mby52biIsImp0aSI6IjJmOTE4YmEwLTQ2ZTAtNDA5OC05ODYyLTY0ODMzYmJjZGI5NiIsIm5hbWVpZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsIm5hbWUiOiJ1c2VyMUBpbmZvLnZuIiwibmJmIjoxNjY2MTY1OTYyLCJleHAiOjE2NjYyNTIzNjIsImlhdCI6MTY2NjE2NTk2Mn0.ceRhYrEVBbhiToXJE0XFWGCSrcATKI5uo4NUs590DVY

{
    "Email": "admin2@info.vn",
    "Password": "admin2_1",
    "Role": "Member"
}
###
PUT https://localhost:7275/users/staff1@info.vn/roles
content-type: application/json

{
    "Role": "Member"
}
###
DELETE https://localhost:7275/users/8e974a41-ffa8-4da4-a326-50b8d0f41252
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsImVtYWlsIjoidXNlcjFAaW5mby52biIsImp0aSI6IjJmOTE4YmEwLTQ2ZTAtNDA5OC05ODYyLTY0ODMzYmJjZGI5NiIsIm5hbWVpZCI6Ijg4YzQ3ZWM3LTA3ODItNDZlOC1iNzExLTViZjIzODQ5NGY4MSIsIm5hbWUiOiJ1c2VyMUBpbmZvLnZuIiwibmJmIjoxNjY2MTY1OTYyLCJleHAiOjE2NjYyNTIzNjIsImlhdCI6MTY2NjE2NTk2Mn0.ceRhYrEVBbhiToXJE0XFWGCSrcATKI5uo4NUs590DVY



### ### ### GetAllRoles
https://localhost:7275/setup
### CreateRole
POST https://localhost:7275/setup?roleName=Admin

