###
https://localhost:7237/api/enrollments
###
POST https://localhost:7237/api/enrollments
content-type: application/json

{
    "Id": "11",
    "UserId": "22",
    "CourseId": "1111"
}
###
PUT https://localhost:7237/api/enrollments/4
content-type: application/json

{
    "Id": 5
}
###
DELETE https://localhost:7237/api/enrollments/99
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### ### ###
httpss://localhost:7237/testPollyCB
###

