###
https://localhost:7131/api/users/2

### ### ###
https://localhost:7237/api/enrollments
###
POST https://localhost:7237/api/enrollments
content-type: application/json

{
    "UserId": "6",
    "CourseId": "2"
}
###
POST https://localhost:7237/api/enrollments/sync
content-type: application/json

{
    "UserId": "9",
    "CourseId": "1"
}
###
PUT https://localhost:7237/api/enrollments/4
content-type: application/json

{
}
###
DELETE https://localhost:7237/api/enrollments/99
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### ### ###
https://localhost:7124/api/reports
###


### ### ###
httpss://localhost:7237/testPollyCB
###

